# Generated by Django 3.1.4 on 2021-06-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210609_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='token_id',
            new_name='user',
        ),
    ]
