# Generated by Django 3.1.4 on 2021-06-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210611_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
